version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - '127.0.0.1:18290:80'
    env_file:
      - .env
    volumes:
      - ./www:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    ports:
      - '127.0.0.1:63306:3306'
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
